/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_malata_factorytest_item_thread_BackLightThread */

#ifndef _Included_com_mlt_factorytest_item_thread_BackLightThread
#define _Included_com_mlt_factorytest_item_thread_BackLightThread
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_malata_factorytest_item_thread_BackLightThread
 * Method:    renewLcdBrightness
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_mlt_factorytest_item_thread_BackLightThread_renewLcdBrightness
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_malata_factorytest_item_thread_BackLightThread
 * Method:    writeLedRed
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_mlt_factorytest_item_thread_BackLightThread_writeLedRed
  (JNIEnv *, jclass);

/*
 * Class:     com_malata_factorytest_item_thread_BackLightThread
 * Method:    writeLedGreen
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_mlt_factorytest_item_thread_BackLightThread_writeLedGreen
  (JNIEnv *, jclass);

/*
 * Class:     com_malata_factorytest_item_thread_BackLightThread
 * Method:    writeKeypadBrightness
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_mlt_factorytest_item_thread_BackLightThread_writeKeypadBrightness
  (JNIEnv *, jclass);


#ifdef __cplusplus
}
#endif
#endif
