/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_malata_factorytest_item_thread_BackLightThread */

#ifndef _Included_com_malata_factorytest_item_thread_BackLightThread
#define _Included_com_malata_factorytest_item_thread_BackLightThread
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_malata_factorytest_item_thread_BackLightThread
 * Method:    LCD_Test
 * Signature: ()V
 */
JNIEXPORT jboolean JNICALL Java_com_malata_factorytest_item_thread_BackLightThread_LCD_1Test
  (JNIEnv *, jobject);

/*
 * Class:     com_malata_factorytest_item_thread_BackLightThread
 * Method:    LED_Test
 * Signature: ()V
 */
JNIEXPORT jboolean JNICALL Java_com_malata_factorytest_item_thread_BackLightThread_LED_1Test
  (JNIEnv *, jobject);

/*
 * Class:     com_malata_factorytest_item_thread_BackLightThread
 * Method:    KEY_Test
 * Signature: ()V
 */
JNIEXPORT jboolean JNICALL Java_com_malata_factorytest_item_thread_BackLightThread_KEY_1Test
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
