/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_malata_factorytest_item_thread_BackLightThread */

#ifndef _Included_com_malata_factorytest_item_thread_BackLightThread
#define _Included_com_malata_factorytest_item_thread_BackLightThread
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_malata_factorytest_item_thread_BackLightThread
 * Method:    LCD_Test
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_malata_factorytest_item_thread_BackLightThread_LCD_1Test
  (JNIEnv *, jobject);

/*
 * Class:     com_malata_factorytest_item_thread_BackLightThread
 * Method:    renewLCD_Brightness
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_malata_factorytest_item_thread_BackLightThread_renewLCD_1Brightness
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_malata_factorytest_item_thread_BackLightThread
 * Method:    LED_Test
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_malata_factorytest_item_thread_BackLightThread_LED_1Test
  (JNIEnv *, jclass);

/*
 * Class:     com_malata_factorytest_item_thread_BackLightThread
 * Method:    KEY_Test
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_malata_factorytest_item_thread_BackLightThread_KEY_1Test
  (JNIEnv *, jclass);

/*
 * Class:     com_malata_factorytest_item_thread_BackLightThread
 * Method:    writeLED_Bright
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_malata_factorytest_item_thread_BackLightThread_writeLED_1Bright
  (JNIEnv *, jclass);

/*
 * Class:     com_malata_factorytest_item_thread_BackLightThread
 * Method:    writeLED_Dark
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_malata_factorytest_item_thread_BackLightThread_writeLED_1Dark
  (JNIEnv *, jclass);

/*
 * Class:     com_malata_factorytest_item_thread_BackLightThread
 * Method:    writeKEYPAD_Bright
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_malata_factorytest_item_thread_BackLightThread_writeKEYPAD_1Bright
  (JNIEnv *, jclass);

/*
 * Class:     com_malata_factorytest_item_thread_BackLightThread
 * Method:    writeKEYPAD_Dark
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_malata_factorytest_item_thread_BackLightThread_writeKEYPAD_1Dark
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
